name: 'Get Version'
description: 'Get version/rev/changelist from github rev and git describe'
inputs:
  versionPattern:
    description: 'glob pattern to recognize valid version tags'
    required: false
    default: '[0-9]*.[0-9].[0-9]'
outputs:
  revision:
    description: 'The version as retrieved from the last tag + eventual updates since that tag'
    value: ${{ steps.get-version.outputs.revision }}
  sha1:
    description: 'The shortened sha1 hash of the commit'
    value: ${{ steps.get-version.outputs.sha1 }}
  changelist:
    description: 'empty for releases, otherwise -SNAPSHOT'
    value: ${{ steps.get-version.outputs.changelist }}
runs:
  using: "composite"
  steps:
    - id: get-version
      shell: bash
      run: ${{ github.action_path }}/version.sh
      env:
        VERSION_PATTERN: ${{ inputs.versionPattern }}
